version: "3.3"
services:
  # nginx to front plausible, letencrypt renewals, and streamstatus.
  nginx:
    # We build a custom nginx container from alpine with a proper nginx.conf
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    restart: always

  # letencrypt to check and regenerate certs.
  letsencrypt:
    image: certbot/certbot:latest
    command: sh -c "while :; do certbot renew --debug -v; R=$$(( ( RANDOM % 604800 )  + 259200 )); echo sleeping $$R seconds...; sleep $$R; done"
    #command: sh -c "certbot certonly --debug --webroot -w /tmp/acme_challenge --expand -d p.infosecstreams.com --text --agree-tos --register-unsafely-without-email --rsa-key-size 4096 --verbose --preferred-challenges=http"
    #command: sh -c "certbot certonly --staging --debug --webroot -w /tmp/acme_challenge --expand -d p.infosecstreams.com --text --agree-tos --register-unsafely-without-email --rsa-key-size 4096 --verbose --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/tmp/acme_challenge:/tmp/acme_challenge"
    environment:
      - TERM=xterm
    restart: unless-stopped
    depends_on:
      - nginx

  # streamstatus to receive event requests from twitch
  streamstatus:
    image: ghcr.io/infosecstreams/streamstatus:latest
    ports:
      - "8080:8080"
    env_file: streamstatus.env
    restart: always
    depends_on:
      - nginx

  # smtp container to send plausible email reports
  mail:
    build:
      context: ./mail
      dockerfile: mail.Dockerfile
    image: bytemark/smtp
    restart: always
    env_file:
      - mail-conf.env

  # plausibles main database
  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - postgres-conf.env

  # plausibles event database
  plausible_events_db:
    image: clickhouse/clickhouse-server:head-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  geoip:
    image: maxmindinc/geoipupdate
    restart: always
    env_file:
      geoip/geoip.env
    volumes:
      - geoip:/usr/share/GeoIP:rw

  # plausible analytics
  plausible:
    image: plausible/analytics:v1
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - geoip
      - plausible_db
      - plausible_events_db
      - mail
      - nginx
    volumes:
      - ./geonames.csv:/etc/app/geonames.csv:ro
      - geoip:/geoip:ro
    env_file:
      - plausible-conf.env

# Our local docker volumes
volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local

 # For detailed migration instructions
 # that were tested via trial by fire
 # check: https://github.com/plausible/analytics/discussions/1911#discussioncomment-5894441
